// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchedulingSystem.Data;

#nullable disable

namespace SchedulingSystem.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    partial class SchedulingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredCourseId")
                        .HasColumnType("integer");

                    b.HasKey("CourseId", "RequiredCourseId");

                    b.HasIndex("RequiredCourseId");

                    b.ToTable("CoursePrerequisite", (string)null);
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CompletedByStudentsId")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedCoursesId")
                        .HasColumnType("integer");

                    b.HasKey("CompletedByStudentsId", "CompletedCoursesId");

                    b.HasIndex("CompletedCoursesId");

                    b.ToTable("StudentCompletedCourse", (string)null);
                });

            modelBuilder.Entity("CourseStudent1", b =>
                {
                    b.Property<int>("AssignedCoursesId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedStudentsId")
                        .HasColumnType("integer");

                    b.HasKey("AssignedCoursesId", "AssignedStudentsId");

                    b.HasIndex("AssignedStudentsId");

                    b.ToTable("StudentAssignedCourse", (string)null);
                });

            modelBuilder.Entity("SchedulingSystem.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CourseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseNumber")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SchedulingSystem.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentCredits")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseAffiliation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxCreditsAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("YearLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoursePrerequisite", b =>
                {
                    b.HasOne("SchedulingSystem.Data.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulingSystem.Data.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("RequiredCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("SchedulingSystem.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("CompletedByStudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulingSystem.Data.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CompletedCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseStudent1", b =>
                {
                    b.HasOne("SchedulingSystem.Data.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("AssignedCoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchedulingSystem.Data.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("AssignedStudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
